version: '3.8'

services:
  ldap:
    image: osixia/openldap:1.5.0
    container_name: ldap
    volumes:
      - ./ldap/bootstrap.ldif:/container/service/slapd/assets/config/bootstrap/ldif/50-bootstrap.ldif:ro
      - ldap-data:/var/lib/ldap
      - ldap-config:/etc/ldap/slapd.d
    environment:
      LDAP_ORGANISATION: "Proyecto"
      LDAP_DOMAIN: "nautilus.proyecto"
      LDAP_ADMIN_PASSWORD: "${LDAP_ADMIN_PASSWORD}"
    ports:
      - "389:389"
      - "636:636"
    restart: unless-stopped

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    env_file:
      - ./backend/.env
    ports:
      - "3000:3000"
    depends_on:
      - ldap
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    env_file:
      - ./frontend/.env
    ports:
      - "80:80"      # Aquí el frontend expuesto en puerto 80 (opcional según nginx)
    depends_on:
      - backend
    restart: unless-stopped

  webrtc:
    build:
      context: ./webrtc
      dockerfile: Dockerfile
    container_name: webrtc
    ports:
      - "8080:8080"
    depends_on:
      - backend
    restart: unless-stopped

  coturn:
    build:
      context: ./coturn
      dockerfile: Dockerfile
    container_name: coturn
    ports:
      - "3478:3478/udp"
      - "5349:5349/tcp"
    restart: unless-stopped

  whiteboard:
    build:
      context: ./whiteboard
      dockerfile: Dockerfile
    container_name: whiteboard
    ports:
      - "4000:4000"
    restart: unless-stopped

  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - frontend
      - backend
      - webrtc
      - whiteboard
    restart: unless-stopped

volumes:
  ldap-data:
  ldap-config:
